-- ═══ TEAM KPI DATA ═══
-- Run after `team_kpis` exists (see schema.sql).
-- Unique (team_member, week_start): re-runs fail unless DELETE/TRUNCATE those rows first.

INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-01-05', '{"creator_messages": 151, "sf_outreach": 23400, "samples_sent": 324, "videos_posted": 1050, "cs_messages": 31, "discord_messages": 15, "starter_15": 6, "starter_30": 6, "mouth_tape": 0, "total_outreach": 12, "wins": "Q_Finds viral level up videos, created partnerships retreat proposal", "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Q_Finds viral level up videos, created partnerships retreat proposal');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-01-12', '{"creator_messages": 116, "sf_outreach": 21700, "samples_sent": 218, "videos_posted": 915, "cs_messages": 16, "discord_messages": 19, "starter_15": 6, "starter_30": 6, "mouth_tape": 1, "total_outreach": 13, "wins": "Brief Template completed!", "ugc_starter_kits": 4, "ugc_mouth_tape": 1, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Brief Template completed!');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-01-19', '{"creator_messages": 104, "sf_outreach": 34100, "samples_sent": 431, "videos_posted": 650, "cs_messages": 16, "discord_messages": 10, "starter_15": 4, "starter_30": 4, "mouth_tape": 4, "total_outreach": 12, "wins": "Flow chart", "ugc_starter_kits": 0, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": false, "top_viral_hooks": false, "viral_sheet": false, "google_drive": false}'::jsonb, 'Flow chart');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-01-26', '{"creator_messages": 34, "sf_outreach": 17400, "samples_sent": 195, "videos_posted": 543, "cs_messages": 3, "discord_messages": 6, "starter_15": 1, "starter_30": 1, "mouth_tape": 1, "total_outreach": 3, "wins": "Flow chart", "tts_ugc_bool": false, "weekly_docs_update": false, "top_viral_hooks": false, "viral_sheet": false, "google_drive": false}'::jsonb, 'Flow chart');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-02-02', '{"creator_messages": 90, "sf_outreach": 18029, "samples_sent": 71, "videos_posted": 701, "cs_messages": 7, "starter_15": 4, "starter_30": 4, "mouth_tape": 4, "total_outreach": 12, "tts_ugc_bool": true, "weekly_docs_update": false, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-02-09', '{"creator_messages": 206, "sf_outreach": 22400, "samples_sent": 67, "videos_posted": 379, "cs_messages": 10, "discord_messages": 2, "starter_15": 8, "starter_30": 2, "mouth_tape": 2, "total_outreach": 12, "tts_ugc_bool": true, "weekly_docs_update": false, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-02-16', '{"creator_messages": 81, "sf_outreach": 55900, "samples_sent": 555, "videos_posted": 399, "cs_messages": 4, "discord_messages": 2, "starter_15": 8, "starter_30": 2, "mouth_tape": 2, "total_outreach": 12, "tts_ugc": 2, "wins": "In Person P/L Doc", "tts_ugc_bool": true, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'In Person P/L Doc');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-02-23', '{"creator_messages": 86, "sf_outreach": 36300, "samples_sent": 323, "videos_posted": 588, "cs_messages": 7, "starter_15": 10, "starter_30": 0, "mouth_tape": 2, "total_outreach": 12, "tts_ugc": 2, "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": true, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-03-02', '{"creator_messages": 58, "sf_outreach": 37400, "samples_sent": 139, "videos_posted": 502, "cs_messages": 10, "starter_15": 10, "starter_30": 0, "mouth_tape": 2, "total_outreach": 12, "tts_ugc": 7, "wins": "Content mining (5 videos)", "ugc_starter_kits": 11, "ugc_mouth_tape": 1, "tts_ugc_bool": true, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Content mining (5 videos)');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-03-09', '{"creator_messages": 44, "sf_outreach": 60700, "samples_sent": 155, "videos_posted": 367, "cs_messages": 3, "discord_messages": 3, "starter_15": 10, "starter_30": 0, "mouth_tape": 2, "total_outreach": 12, "tts_ugc": 4, "wins": "Content mining (5 videos)", "ugc_starter_kits": 10, "ugc_mouth_tape": 0, "tts_ugc_bool": true, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Content mining (5 videos)');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-03-16', '{"creator_messages": 73, "sf_outreach": 38200, "samples_sent": 83, "videos_posted": 279, "cs_messages": 7, "discord_messages": 1, "starter_15": 10, "starter_30": 0, "mouth_tape": 2, "total_outreach": 12, "tts_ugc": "2 (posted less bc of event posts overflowing feed)", "wins": "Content mining (10 videos)", "ugc_starter_kits": 4, "ugc_mouth_tape": 1, "tts_ugc_bool": true, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Content mining (10 videos)');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-03-23', '{"creator_messages": 24, "sf_outreach": 35100, "samples_sent": 32, "videos_posted": 202, "cs_messages": 3, "discord_messages": 1, "starter_15": 10, "starter_30": 0, "mouth_tape": 2, "total_outreach": 12, "tts_ugc": "1 (had issue with penalties)", "wins": "Content mining (10 videos)", "ugc_starter_kits": 6, "ugc_mouth_tape": 0, "tts_ugc_bool": true, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Content mining (10 videos)');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2026-03-30', '{"creator_messages": 16, "cs_messages": 4, "tts_ugc_bool": false, "weekly_docs_update": false, "top_viral_hooks": false, "viral_sheet": false, "google_drive": false}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-09-01', '{"creator_messages": 25, "sf_outreach": 21800, "samples_sent": 180, "videos_posted": 501, "cs_messages": 16, "ugc_starter_kits": 4, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": false, "viral_sheet": false, "google_drive": false}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-09-08', '{"creator_messages": 55, "sf_outreach": 17300, "samples_sent": 182, "videos_posted": 615, "cs_messages": 19, "starter_15": 28, "starter_30": 28, "mouth_tape": 28, "total_outreach": 84, "ugc_starter_kits": 2, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": false, "viral_sheet": false, "google_drive": false}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-09-15', '{"creator_messages": 31, "sf_outreach": 8900, "samples_sent": 74, "videos_posted": 441, "cs_messages": 13, "ugc_starter_kits": 7, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-09-22', '{"creator_messages": 47, "sf_outreach": 12400, "samples_sent": 105, "videos_posted": 397, "cs_messages": 5, "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-09-29', '{"creator_messages": 70, "sf_outreach": 43300, "samples_sent": 431, "videos_posted": 394, "cs_messages": 10, "starter_15": 28, "starter_30": 28, "mouth_tape": 28, "total_outreach": 84, "ugc_starter_kits": 5, "ugc_mouth_tape": 4, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-10-06', '{"creator_messages": 193, "sf_outreach": 35400, "samples_sent": 806, "videos_posted": 507, "cs_messages": 23, "starter_15": 28, "starter_30": 28, "mouth_tape": 28, "total_outreach": 84, "ugc_starter_kits": 5, "ugc_mouth_tape": 3, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-10-13', '{"creator_messages": 207, "sf_outreach": 38500, "samples_sent": 422, "videos_posted": 1038, "cs_messages": 25, "starter_15": 28, "starter_30": 28, "mouth_tape": 28, "total_outreach": 84, "ugc_starter_kits": 11, "ugc_mouth_tape": 1, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-10-20', '{"creator_messages": 185, "sf_outreach": 32300, "samples_sent": 307, "videos_posted": 822, "cs_messages": 37, "starter_15": 9, "starter_30": 9, "mouth_tape": 3, "total_outreach": 21, "wins": "1K GMV Creator Tracker doc created", "ugc_starter_kits": 9, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, '1K GMV Creator Tracker doc created');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-10-27', '{"creator_messages": 196, "sf_outreach": 41000, "samples_sent": 756, "videos_posted": 786, "cs_messages": 9, "starter_15": 11, "starter_30": 14, "mouth_tape": 10, "total_outreach": 35, "wins": "Target invite numbers fixed by spreading out invites?", "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Target invite numbers fixed by spreading out invites?');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-11-03', '{"creator_messages": 276, "sf_outreach": 33800, "samples_sent": 582, "videos_posted": 1062, "cs_messages": 31, "starter_15": 4, "starter_30": 4, "mouth_tape": 4, "total_outreach": 12, "wins": "Created 12 target collab invites to ensure optimization", "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Created 12 target collab invites to ensure optimization');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-11-10', '{"creator_messages": 219, "sf_outreach": 35300, "samples_sent": 699, "videos_posted": 856, "cs_messages": 22, "starter_15": 4, "starter_30": 4, "mouth_tape": 4, "total_outreach": 12, "wins": "Created level up trend doc", "ugc_starter_kits": 8, "ugc_mouth_tape": 1, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Created level up trend doc');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-11-17', '{"creator_messages": 340, "sf_outreach": 49700, "samples_sent": 892, "videos_posted": 980, "cs_messages": 54, "discord_messages": 5, "starter_15": 4, "starter_30": 4, "mouth_tape": 4, "total_outreach": 12, "wins": "More issues with Superfiliate, started up Discord", "ugc_starter_kits": 7, "ugc_mouth_tape": 1, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'More issues with Superfiliate, started up Discord');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-11-24', '{"creator_messages": 192, "sf_outreach": 37400, "samples_sent": 798, "videos_posted": 893, "cs_messages": 44, "discord_messages": 16, "starter_15": 1, "starter_30": 1, "mouth_tape": 1, "total_outreach": 3, "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-12-01', '{"creator_messages": 146, "sf_outreach": 34100, "samples_sent": 747, "videos_posted": 1005, "cs_messages": 52, "discord_messages": 14, "starter_15": 4, "starter_30": 4, "mouth_tape": 4, "total_outreach": 12, "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-12-08', '{"creator_messages": 179, "sf_outreach": 42100, "samples_sent": 755, "videos_posted": 1038, "cs_messages": 27, "discord_messages": 6, "starter_15": 4, "starter_30": 4, "mouth_tape": 4, "total_outreach": 12, "wins": "Looked through 1,000 videos in the span of two days", "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Looked through 1,000 videos in the span of two days');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-12-15', '{"creator_messages": 294, "sf_outreach": 48200, "samples_sent": 1000, "videos_posted": 1340, "cs_messages": 39, "discord_messages": 10, "starter_15": 4, "starter_30": 4, "mouth_tape": 4, "total_outreach": 12, "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, NULL);
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-12-22', '{"creator_messages": 127, "sf_outreach": 36000, "samples_sent": 708, "videos_posted": 1083, "cs_messages": 21, "discord_messages": 8, "starter_15": 4, "starter_30": 4, "mouth_tape": 4, "total_outreach": 12, "wins": "Filled in for Jackie in Sprout", "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Filled in for Jackie in Sprout');
INSERT INTO team_kpis (team_member, week_start, data, wins) VALUES ('Ashleigh Pierce', '2025-12-29', '{"creator_messages": 117, "sf_outreach": 8100, "samples_sent": 148, "videos_posted": 1019, "cs_messages": 14, "discord_messages": 7, "starter_15": 1, "starter_30": 2, "mouth_tape": 1, "total_outreach": 4, "wins": "Filled in for Jackie in Sprout", "ugc_starter_kits": 5, "ugc_mouth_tape": 0, "tts_ugc_bool": false, "weekly_docs_update": true, "top_viral_hooks": true, "viral_sheet": true, "google_drive": true}'::jsonb, 'Filled in for Jackie in Sprout');
